AllCops:
    TargetRubyVersion: 2.6
    Exclude:
        - 'db/**/*'
        - 'node_modules/**/*'
        - 'vendor/**/*'
        - 'bin/**/*'
    NewCops: enable

require:
    - rubocop-minitest
    - rubocop-performance
    - rubocop-rake

Layout/LineLength:
    Max: 120

Metrics/BlockLength:
    Max: 70

Metrics/MethodLength:
    Max: 20

Metrics/AbcSize:
    Max: 20

Layout/TrailingEmptyLines:
    EnforcedStyle: 'final_newline'

Style/HashTransformValues:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true

Style/HashEachMethods:
    Enabled: true
