name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1 # uses .ruby-version file
      with:
        bundler-cache: true
    - name: Run Linters
      run: bundle exec rubocop
    - name: Run Test Suite
      run: |
        bundle exec rake db:migrate
        bundle exec rake test
      env:
        RACK_ENV: test
